apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-app-of-apps-test
  labels:
    env: test
    type: app-of-apps
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  project: online-boutique
  source:
    path: argocd-applications/test
    repoURL: https://github.com/aminerachyd/multiarch-build-pipeline.git
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
