variable "project-name" {}
variable "x86-module-name" {}
variable "z-module-name" {}
variable "power-module-name" {}
variable "cluster-host" {}
variable "cluster-token" {}
variable "registry-user" {}
variable "registry-token" {}
variable "gitops-repo" {}
variable "git-user" {}
variable "git-token" {}
