apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build
spec:
  params:
    - name: git-url
      type: string
  steps:
  - name: build-step
    image: registry.access.redhat.com/ubi8/ubi
    command:
    - /bin/bash
    - -c
    - |
      echo 'Git url of the repo $(params.git-url)'
