apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-push
spec:
  params:
    - description: The url for the git repository
      name: git-url
      type: string
  tasks:
  - name: build
    params:
      - name: git-url
        value: $(params.git-url)
    taskRef:
      kind: Task
      name: build
