apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-prod
  labels:
    env: prod
spec:
  destination:
    name: opal | ppc64le on-prem
    namespace: multiarch-demo-prod
  project: online-boutique
  source:
    helm:
      parameters:
      - name: frontend.namespaceToDeploy
        value: multiarch-demo-prod
    path: frontend
    repoURL: https://github.com/aminerachyd/multiarch-build-gitops.git
    targetRevision: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - PruneLast=true
