# Tekton task for testing go
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: testgolang
  labels:
    task.knative.dev/creator: testgolang
    task.knative.dev/test-runner: "true"
spec:
  steps:
    - name: git-clone
      image: docker.io/mattn/go-test-golang:1.13.3
      script: |
        set -eux
        git clone
    - name: testgolang
      image: golang:1.14.2
      workingDir: /workspace
      command:
        - /bin/sh
        - -c
        - |
          set -x
          go test -v
