variable "project-name" {}
variable "x86-module-name" {}
variable "z-module-name" {}
variable "power-module-name" {}
variable "cluster-host" {}
variable "cluster-token" {}
variable "registry-user" {}
variable "registry-token" {}
variable "x86-cluster-host" {}
variable "power-cluster-host" {}
variable "z-cluster-host" {}
